### ISSUE TITLE
Improve ContextModel serialization to support file

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT-IDE#11]
### Why
Following the progress in #4, the consert.txt support file needs to have a well defined structure, whereby ContextEntities and ContextAssertions can be clearly identified.

### What
  - [x] add list of ContextEntities
  - [x] add list of ContextAssertions

**Comment by AlinGabriel** [comment]
done in this commit: https://github.com/ami-lab/CONSERT-IDE/commit/a0d5b25f1dfbd32b3d89f25cacd6ff942da775ba

**Comment by AlinGabriel** [comment]
and updated the json parser to add new models in the corresponding lists: https://github.com/ami-lab/CONSERT-IDE/commit/07db1a7f8828124b1216d741eae2121f359f7dfc
