### ISSUE TITLE
Investigate Creation of Form Panel for editing/viewing ContextEntities and ContextAssertions

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT-IDE#15]
### Why
Following the outlines set in #7, we need to define a form-based editor for the properties of a ContextEntity.
When a ContextEntity is opened (double-click) for view/edit from the TreeView, the CONSERT Perspective needs to allow opening of a form-based editor in the central panel.

### What
  - [ ] document detailing how to open a form based editor when selecting to view/edit a ContextEntity

**Comment by AlinGabriel** [comment]
done
