### ISSUE TITLE
Implement Persistence after form view edit

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT-IDE#18]
### What
  - serialize changes to ContextAssertion and ContextEntity elements to `consert.txt` support file.

**Comment by AlinGabriel** [comment]
changes from the formView or from the source view or both ?

**Comment by asorici** [comment]
Start with the changes from the FormView, since that is easier.
For changes from the source view, you have to consider validating them by trying to de-serialize a ContextEntity or ContextAssertion object using the Jackson library. The deserialzed object is updated in the ProjectModel and then that model is persisted in the origin.txt file.

**Comment by AlinGabriel** [comment]
So basically the source view would update only the ProjectModel ? Not
persist the modifications directly ? It should mark the formView dirty ?
and after you save the formView persist the model ?


On Fri, Aug 18, 2017 at 10:43 AM, Alexandru Sorici <notifications@github.com

**Comment by AlinGabriel** [comment]
working on it
