### ISSUE TITLE
Implement project wide ContextModel

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT-IDE#26]
### Why
A project wide model containing the created ContextEntities and ContextAssertions is required.
The model can then be referenced in all views (e.g. TreeView, FormView, TextEditorView).

### What
  - implement a singleton style class that holds the ContextModel created within a project
  - include methods for:
    - getting list of ContextEntities and ContextAssertions
    - getting ContextEntity/ContextAssertion by name
    - add/remove ContextEntity and ContextAssertion

**Comment by AlinGabriel** [comment]
done
