### ISSUE TITLE
Proper WorkspaceModel initialization

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT-IDE#39]
### Why
In the design of the CONSERT IDE, the WorkspaceModel plays an essential role in initialization.
Upon startup of the CONSERT IDE, the WorkspaceModel is in charge of inspecting the Eclipse-managed workspace, looking for all projects that have the `CONSERT` project nature.
Currently, loading and initialization of these projects is performed upon accessing certain GUI elements (e.g. a FormView for the consert.txt file).
Initialization of the ProjectModels needs to be independent of any GUI events.

### What
  - make all ProjectModel initialization code independent of any GUI events
  - create helper functions within WorkspaceModel which allow determining what the currently active project is

**Comment by emiliapopa** [comment]
WorkspaceModel initialization code has been done independent of any GUI events.
The initialization takes place when the initial layout for ConsertPerspective takes place.
ProjectModel instances are also populated with elements of the model which exist in the corresponding text files.

**Comment by emiliapopa** [comment]
Solved 8 days ago.
