### ISSUE TITLE
Determine current active project

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT-IDE#40]
### Why
In relation to the story outlined in #39, we want to be able to determine at all times what the currently selected project is. This is useful for every widget whose outcome is the addition of a new element to the context model of a project.

### What
  - [x] implement means to retrieve current project by inspecting selected files in the Package Explorer
  - [x] implement means to retrieve current project by inspecting selected entries in the CONSERT TreeView
  - [x] create helper functions at the level of the WorkspaceModel that can be accessed anywhere in the code to determine current project using the mechanisms mentioned above

**Comment by emiliapopa** [comment]
Solved 8 days ago.
