### ISSUE TITLE
Pass ProjectModel to ContextElement form view upon selection in TreeView 

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT-IDE#41]
### Why
Since the current project can be easily determined upon a selection in the TreeView, this information can be passed to the wrapper handling the editing of the chosen context model element (ContextEntity or ContextAssertion).
This avoids having to reinspect the current TreeView selection later on.

### What
  - pass ProjectModel information to the wrapper handling the display/editing of the selected context model element

**Comment by AlinGabriel** [comment]
Didn't we do this last tuesday ?

**Comment by AlinGabriel** [comment]
done
