### ISSUE TITLE
ContextModel element creation wizzards need not ask for project name

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT-IDE#42]
### Why
As a developer, I want as much boilerplate automation as possible. When launching _New ..._ type widgets, the project name should be automatically determined whenever this possibility exists.

### What
  - [x] automatically fill in the project name and path, whenever determining the currently active project can be done (cf. issues #39 and #40).

**Comment by emiliapopa** [comment]
When launching a ContextModel element creation wizzard, the getCurrentActiveProject  method from WorkspaceModel is called to determine which project is the currently active project.
For future ContextModel element creation wizzards, the same method may be used.

**Comment by emiliapopa** [comment]
Solved 8 days ago.
