### ISSUE TITLE
Implement context menu for New ContextAssertion/ContextEntity on TreeView

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT-IDE#43]
### Why
As a developer of a context model using the CONSERT IDE, I want to find useful menu shortcuts at my disposal for creating new context model elements. Since the TreeView is an essential GUI element of the CONSERT IDE, context menus for creating new ContextEntities and ContextAssertions are required.

### What
  - implement the option to launch the ContextEntity/Assertion creation wizzards from entries in a context menu (right click menu) attached to the corresponding nodes in the TreeView

**Comment by AlinGabriel** [comment]
done
