### ISSUE TITLE
Defer all save-to-disk calls to ProjectModel

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT-IDE#44]
### Why
Currently, persistence of changes made to an element of a context model is handled in the class implementing the GUI that helps edit those changes.
This brings about difficulties in refreshing all other GUI views that are affected by the change.
Consequently, actual persistence calls are deferred to the ProjectModel supporting the modified context element. This way, the project model can notify all dependent views of the newly made change.

### What
  - design and implement mechanism to defer and perform persistence of context model element changes in the corresponding ProjectModel

**Comment by AlinGabriel** [comment]
done
