### ISSUE TITLE
ContextAssertionModel refactored after BinaryContextAssertion

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT-IDE#48]
### Why
The CONSERT IDE needs to output RDF and OOP (Java Classes) forms of the modeled context elements. These need to precisely follow the CONSERT Meta Model.

To take a step in this direction, the current simple models for a ContextAssertion is upgraded to follow the model of a [BinaryContextAssertion](https://github.com/ami-lab/CONSERT/blob/master/consert-engine/src/main/java/org/aimas/consert/model/content/BinaryContextAssertion.java).

### What
  - [x] include field for subjectEntity
  - [x] include field for objectEntity
  - [x] include field for acquisitionType (SENSED, PROFILED or DERIVED)

### Notes
The update needs to be reflected at model level (ContextAssertionModel) as well as in the GUI elements (ContextAssertion creation wizzard and FormView).

**Comment by AlinGabriel** [comment]
done
