### ISSUE TITLE
Add functionality for TreeView of created ContextEntities and ContextAssertions

### ISSUE THREAD

**Issue by asorici** [ami-lab/CONSERT-IDE#6]
## WHY
Following plan in #5 we need to create functionality for viewing ContextEntities and ContextAssertions of a CONSERT project in the let side panel which usually allows exploration of project contents.

## WHAT
  - [x] View similar to package explorer in Java Perspective is implemented
  - [x] Ability to open a Wizard for new ContextEntity / ContextAssertion is implemented
      - wizard will fill in the following fields:
        - for ContextEntitiy: name (required), comment (optional)
        - for ContextAssertion: name (required), comment (optional), arity (required), list of ContextEntities (optional)

**Comment by AlinGabriel** [comment]
will start working on this

**Comment by asorici** [comment]
Initial views for the ContextModelDefinition have been made. Display of created assertions and entities is continued in follow-up #13.
Closing, thank you!
